language: python

# Default environment: Ubuntu Trusty 14.04.
os: linux
dist: trusty

# Default job task: run tests as defined in the $OPT environment variable.
# Jobs can redefine the 'script' stage in the matrix below.
script: scripts/runtests.py $OPTS
